// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entries.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (id, created_at, updated_at, rcsb_id,deposit_date,doi,paper_title,method,user_group)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, created_at, updated_at, rcsb_id, deposit_date, doi, paper_title, method, user_group
`

type CreateEntryParams struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	RcsbID      string
	DepositDate string
	Doi         string
	PaperTitle  string
	Method      string
	UserGroup   string
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.RcsbID,
		arg.DepositDate,
		arg.Doi,
		arg.PaperTitle,
		arg.Method,
		arg.UserGroup,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RcsbID,
		&i.DepositDate,
		&i.Doi,
		&i.PaperTitle,
		&i.Method,
		&i.UserGroup,
	)
	return i, err
}

const getEntry = `-- name: GetEntry :one
SELECT id, created_at, updated_at, rcsb_id, deposit_date, doi, paper_title, method, user_group FROM entries WHERE rcsb_id=$1
`

func (q *Queries) GetEntry(ctx context.Context, rcsbID string) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntry, rcsbID)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RcsbID,
		&i.DepositDate,
		&i.Doi,
		&i.PaperTitle,
		&i.Method,
		&i.UserGroup,
	)
	return i, err
}

const getEntryByUserGroup = `-- name: GetEntryByUserGroup :many
SELECT id, created_at, updated_at, rcsb_id, deposit_date, doi, paper_title, method, user_group FROM entries WHERE user_group=$1
`

func (q *Queries) GetEntryByUserGroup(ctx context.Context, userGroup string) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, getEntryByUserGroup, userGroup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RcsbID,
			&i.DepositDate,
			&i.Doi,
			&i.PaperTitle,
			&i.Method,
			&i.UserGroup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertGroup = `-- name: InsertGroup :one
UPDATE entries SET user_group=$1 WHERE rcsb_id=$2 RETURNING id, created_at, updated_at, rcsb_id, deposit_date, doi, paper_title, method, user_group
`

type InsertGroupParams struct {
	UserGroup string
	RcsbID    string
}

func (q *Queries) InsertGroup(ctx context.Context, arg InsertGroupParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, insertGroup, arg.UserGroup, arg.RcsbID)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RcsbID,
		&i.DepositDate,
		&i.Doi,
		&i.PaperTitle,
		&i.Method,
		&i.UserGroup,
	)
	return i, err
}

const removeGroup = `-- name: RemoveGroup :one
UPDATE entries SET user_group='' WHERE rcsb_id=$1 RETURNING id, created_at, updated_at, rcsb_id, deposit_date, doi, paper_title, method, user_group
`

func (q *Queries) RemoveGroup(ctx context.Context, rcsbID string) (Entry, error) {
	row := q.db.QueryRowContext(ctx, removeGroup, rcsbID)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RcsbID,
		&i.DepositDate,
		&i.Doi,
		&i.PaperTitle,
		&i.Method,
		&i.UserGroup,
	)
	return i, err
}
