// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Entry struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	RcsbID      string
	DepositDate string
	Doi         string
	PaperTitle  string
	Method      string
	UserGroup   string
}

type NonPolymer struct {
	ID                uuid.UUID
	EntryID           uuid.UUID
	Nonpolname        string
	CompID            string
	Nonpoldescription string
	FormulaWeight     float32
	NumberOfMolecules int32
	CreatedAt         time.Time
}

type Polymer struct {
	ID                uuid.UUID
	EntryID           uuid.UUID
	Poldescription    string
	Poltype           string
	Polsequence       string
	Pollength         int32
	Formulaweight     float32
	Source            string
	Host              string
	NumberOfMolecules int32
	CreatedAt         time.Time
}
