// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: poly_and_non_poly.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createNonPoly = `-- name: CreateNonPoly :one
INSERT INTO non_polymers (id, entry_id, nonpolname, comp_id,nonpoldescription,formula_weight,number_of_molecules,created_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, entry_id, nonpolname, comp_id, nonpoldescription, formula_weight, number_of_molecules, created_at
`

type CreateNonPolyParams struct {
	ID                uuid.UUID
	EntryID           uuid.UUID
	Nonpolname        string
	CompID            string
	Nonpoldescription string
	FormulaWeight     float32
	NumberOfMolecules int32
	CreatedAt         time.Time
}

func (q *Queries) CreateNonPoly(ctx context.Context, arg CreateNonPolyParams) (NonPolymer, error) {
	row := q.db.QueryRowContext(ctx, createNonPoly,
		arg.ID,
		arg.EntryID,
		arg.Nonpolname,
		arg.CompID,
		arg.Nonpoldescription,
		arg.FormulaWeight,
		arg.NumberOfMolecules,
		arg.CreatedAt,
	)
	var i NonPolymer
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.Nonpolname,
		&i.CompID,
		&i.Nonpoldescription,
		&i.FormulaWeight,
		&i.NumberOfMolecules,
		&i.CreatedAt,
	)
	return i, err
}

const createPoly = `-- name: CreatePoly :one
INSERT INTO polymers (id, entry_id, poldescription, poltype,polsequence,pollength,formulaweight,source,host,number_of_molecules,created_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING id, entry_id, poldescription, poltype, polsequence, pollength, formulaweight, source, host, number_of_molecules, created_at
`

type CreatePolyParams struct {
	ID                uuid.UUID
	EntryID           uuid.UUID
	Poldescription    string
	Poltype           string
	Polsequence       string
	Pollength         int32
	Formulaweight     float32
	Source            string
	Host              string
	NumberOfMolecules int32
	CreatedAt         time.Time
}

func (q *Queries) CreatePoly(ctx context.Context, arg CreatePolyParams) (Polymer, error) {
	row := q.db.QueryRowContext(ctx, createPoly,
		arg.ID,
		arg.EntryID,
		arg.Poldescription,
		arg.Poltype,
		arg.Polsequence,
		arg.Pollength,
		arg.Formulaweight,
		arg.Source,
		arg.Host,
		arg.NumberOfMolecules,
		arg.CreatedAt,
	)
	var i Polymer
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.Poldescription,
		&i.Poltype,
		&i.Polsequence,
		&i.Pollength,
		&i.Formulaweight,
		&i.Source,
		&i.Host,
		&i.NumberOfMolecules,
		&i.CreatedAt,
	)
	return i, err
}

const getNonPolys = `-- name: GetNonPolys :many
SELECT non_polymers.id, non_polymers.entry_id, non_polymers.nonpolname, non_polymers.comp_id, non_polymers.nonpoldescription, non_polymers.formula_weight, non_polymers.number_of_molecules, non_polymers.created_at FROM non_polymers JOIN entries ON non_polymers.entry_id = entries.id WHERE entries.rcsb_id=$1
`

func (q *Queries) GetNonPolys(ctx context.Context, rcsbID string) ([]NonPolymer, error) {
	rows, err := q.db.QueryContext(ctx, getNonPolys, rcsbID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NonPolymer
	for rows.Next() {
		var i NonPolymer
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.Nonpolname,
			&i.CompID,
			&i.Nonpoldescription,
			&i.FormulaWeight,
			&i.NumberOfMolecules,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPolys = `-- name: GetPolys :many
SELECT polymers.id, polymers.entry_id, polymers.poldescription, polymers.poltype, polymers.polsequence, polymers.pollength, polymers.formulaweight, polymers.source, polymers.host, polymers.number_of_molecules, polymers.created_at FROM polymers JOIN entries ON polymers.entry_id = entries.id WHERE entries.rcsb_id=$1
`

func (q *Queries) GetPolys(ctx context.Context, rcsbID string) ([]Polymer, error) {
	rows, err := q.db.QueryContext(ctx, getPolys, rcsbID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Polymer
	for rows.Next() {
		var i Polymer
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.Poldescription,
			&i.Poltype,
			&i.Polsequence,
			&i.Pollength,
			&i.Formulaweight,
			&i.Source,
			&i.Host,
			&i.NumberOfMolecules,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
